{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-02-21",
    "AffectedVersionRange": "*",
    "Summary": "ArbitaryCodeExecution",
    "Contributor": {
        "Discloser": "B3EF",
        "Fixer": ""
    },
    "Package": {
        "Registry": "pip",
        "Name": "altair",
        "URL": "https://pypi.org/project/altair",
        "Downloads": ""
    },
    "CWEs": [
        {
            "ID": "471",
            "Description": "ArbitaryCodeExecution"
        }
    ],
    "CVSS": {
        "Version": "3.0",
        "AV": "N",
        "AC": "L",
        "PR": "N",
        "UI": "N",
        "S": "U",
        "C": "N",
        "I": "N",
        "A": "H",
        "E": "F",
        "RL": "X",
        "RC": "X",
        "Score": "8.9"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/altair-viz/altair",
        "Codebase": [
            "Python"
        ],
        "Owner": "altair",
        "Name": "altair",
        "Stars": "",
        "Forks": ""
    },
    "Permalinks": [
        "https://github.com/altair-viz/altair/blob/master/altair/_magics.py#L123"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1942"
}
